development:
  adapter: postgresql
  database: photr_development

test:
  adapter: postgresql
  database: photr_test

production:
  adapter: postgresql
  encoding: unicode
  database: photr_production
  pool: 5
  username: photr
  password:
